dist: trusty
language: java
jdk: openjdk15
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
